[build]
  base = "./frontend"          # Frontend directory
  publish = "build"            # Build output directory
  command = "npm run build"    # Build command


[functions]
  directory = "backend/netlify/functions"  # Directory for Netlify functions
  node_bundler = "esbuild"                 # Use esbuild for bundling functions

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200